config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'

  get 'movember', to: 'pages#movember'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def index
	end

	def movember
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<div id="contactwrap">
	<div class="container">
		<div class="row-centered">
			<div class="col-lg-12">
				<p>CONTACT ME</p>
				
					<%= mail_to "stealthmark@gmail.com",'stealthmark@gmail.com' %>
					<p>
					Kennett Square, PA
					USA</p>
					</p>
					<p>Website design by Mark Rybarczyk</p>
					<p>copyright 2016</p>
		
			</div>
		</div><!--/row -->
	</div><!-- /container -->
</div>

app/views/layouts/_header.html.erb
<div class="container">
<nav class="navbar navbar-default navbar-fixed-top navbar-inverse" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Mark Rybarczyk", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to "Movember", movember_path %>
        </li>
      </ul>
    </div>
   
  </div><!-- /.container-fluid -->
</nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mark Rybarczyk</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
	<%= render 'layouts/header' %>

<%= yield %>

	<%= render 'layouts/footer' %>
</body>
</html>

app/views/pages/index.html.erb
<section id="home" name="home"></section>
	<div id="headerwrap">
		<div class="container">
			<div class="row">
				<div class="col-md-6 col-md-offset-3">
					<h1>Mark Rybarczyk</h1>
				</div>
			</div><!--/row -->
		</div><!--/container -->
	</div><!--/headerwrap -->
	
	<section id="about" name="about"></section>
	<div id="aboutwrap">
		<div class="container">
			<div class="row">
				<div class="col-lg-4 name">
					<%= image_tag 'mark_anabel_arches1.jpg', class: "img-responsive" %>
					<p>Mark Rybarczyk</p>
					<div class="name-label"></div>
				</div><!--/col-lg-4-->
				<div class="col-lg-8 name-desc">
					<h2>	ENTREPRENEUR <br/> STARTUP GUY <br/>RAILS DEVELOPER <br/> <!-- FINANCIAL --> </h2>
					
					<div class="col-md-6">
						<p>First and foremost, I am an entrepreneur. I created my first two companies from scratch, both in the financial services sector, which I operated over a period of 15 years. </p>
						<p>I've always been proud of my perseverance to overcome obstacles thrown my way in both business and in life. </p>
						<p>Passionate about all things tech related and web related I have been living the startup life for the past six years. 
						</p>
					</div>
					<div class="col-md-6">
						
						<p>My frustration with outsourced developers was the inspiration I needed to teach myself web development and I have completely re-built my own site Vuier in Ruby on Rails along with my Co-Founder/CTO.
						</p>
						<p>In my spare time you can find me on the ice hockey rink, skiing, exercising or spending time with my wife and 3 beautiful girls.</p>
						<p><a class="twitter-follow-button"
							  href="https://twitter.com/markrybarczyk"
							  data-show-count="true"
							  data-lang="en">
							Follow @MarkRybarczyk
							</a>
							<script type="text/javascript">
							window.twttr = (function (d, s, id) {
							  var t, js, fjs = d.getElementsByTagName(s)[0];
							  if (d.getElementById(id)) return;
							  js = d.createElement(s); js.id = id;
							  js.src= "https://platform.twitter.com/widgets.js";
							  fjs.parentNode.insertBefore(js, fjs);
							  return window.twttr || (t = { _e: [], ready: function (f) { t._e.push(f) } });
							}(document, "script", "twitter-wjs"));
							</script>
						</p>
						<p>Connect with me on LinkedIn <%= link_to image_tag('linkedin.png', class: 'img-responsive'), 'https://www.linkedin.com/in/markrybarczyk', alt: "Mark Rybarczyk", target: "_blank" %>
						</p>
						<!-- <p> Follow me @MarkRybarczyk</p> -->
					</div>
					
				</div><!--/col-lg-8-->
		
			</div><!-- /row -->
		</div><!-- /container -->
	</div> <!-- /aboutwrap
	
	<!-- ABOUT SEPARATOR -->
	
	<!-- PORTFOLIO SECTION -->
	<section id="portfolio" name="portfolio"></section>
	<div id="portfoliowrap">
		<div class="container">
			<div class="row row-centered">
			<!-- <div class="row"> -->
				<h1>SOME OF MY LATEST WORKS</h1>
					<div class="col-xs-4 col-centered"><%= link_to image_tag('vuier.png', class: 'img-responsive'), 'https://vuier.com/', alt: "Vuier", target: '_blank' %><h4><%= link_to "Vuier.com", "vuier.com", alt: "vuier", target: '_blank' %></h4></div>
	        <div class="col-xs-4 col-centered"><%= link_to image_tag('graybox.png', class: 'img-responsive'), 'https://graybox.io/', alt: "Graybox", target: '_blank' %><h4><%= link_to "GrayBox", "https://graybox.io/", alt: "graybox", target: '_blank' %></h4></div>
	        <div class="col-xs-4 col-centered"><%= link_to image_tag('dt_image.png', class: 'img-responsive'), 'http://www.thediscounttherapist.com/', alt: "Discount Therapist Episode 3", target: "_blank" %><h4><%= link_to "Discount Therapist", "www.thediscounttherapist.com", target: "_blank" %></h4></div>
							
				<!-- </div> -->
			</div><!-- video-inline --><!-- /row -->
		</div><!--/container -->
	</div>
	</div><!--/Portfoliowrap -->
	<div class="container">
		<!-- <h3>Download my <strong> --><%#link_to "resume", "https://s3.amazonaws.com/Mark_Test_Bucket/MarkRybarczykResume.pdf", target: "_blank", class: "btn btn-primary" %><!-- </strong> 
		</h3>  -->
		
	</div>
	<!-- CONTACT SEPARATOR -->
	
	
	
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
	<script src="assets/js/classie.js"></script>
  <script src="assets/js/bootstrap.min.js"></script>
  <script src="assets/js/smoothscroll.js"></script>
	<script src="assets/js/jquery.stellar.min.js"></script>
	<script src="assets/js/fancybox/jquery.fancybox.js"></script>    
	<script src="assets/js/main.js"></script>
		<script>
		$(function(){
			$.stellar({
				horizontalScrolling: false,
				verticalOffset: 40
			});
		});
		</script>
		
		<script type="text/javascript">
      $(function() {
        //    fancybox
          jQuery(".fancybox").fancybox();
      });
	   </script>

app/views/pages/movember.html.erb
		<div id="movember">
			<div class="container">
				<div class="row">
					<div class="col-md-6 col-md-offset-3">
						<h1>Support the Men of Movember</h1>
					</div>
				</div>
			</div> 
		</div><!--/movember --> 

		<div class="container">
			<h1>The Men of Movember</h1>
			<div class="row">
			  <div class="col-md-offset-1 col-md-10">
			    <div class="panel panel-default center">
			      <div class="panel-body">
			      	<div class="youtube">
			      		<div class="flex-video widescreen">
									<iframe width="913" height="510" src="https://vuier.com/v/the-men-of-movember-4d5e2d81-038b-4a57-a6aa-d124780eea18?embed=true" frameborder="0" allowfullscreen></iframe><br />
								</div>
								<h4 class="centered">We sacrificed one month of our lives to grow a moustache in support of Movember. Please support the men of Vuier and Walnut St Labs in our efforts with a generous donation of which 100% of all revenues will be donated to Movember. Your support is greatly appreciated and we promise that you will be thoroughly entertained in less than six minutes!</h4>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>

	<section id="portfolio" name="portfolio"></section>
		<div id="portfoliowrap">
			<div class="container">
				<div class="row row-centered">
					<h1>SELECT YOUR LEVEL OF SUPPORT</h1>
						<div class="col-xs-4 col-centered"><%= link_to image_tag('MovemberThumbnail.png', class: 'img-responsive'), "https://vuier.com/v/the-men-of-movember", alt: "Men of Movember" %><h4><%= link_to "Support for 99 cents", "https://vuier.com/v/the-men-of-movember" %></h4></div>
		        <div class="col-xs-4 col-centered"><%= link_to image_tag('movember2.png', class: 'img-responsive'), "https://vuier.com/v/the-men-of-movember-40cd6c0e-26f8-43c5-9c66-a20164f5f0eb", alt: "Men of Movember" %><h4><%= link_to "Support for $9.99", "https://vuier.com/v/the-men-of-movember-40cd6c0e-26f8-43c5-9c66-a20164f5f0eb" %></h4></div>
		        <div class="col-xs-4 col-centered"><%= link_to image_tag('MovemberThumbnail.png', class: 'img-responsive'), "https://vuier.com/v/the-men-of-movember-4d5e2d81-038b-4a57-a6aa-d124780eea18", alt: "Men of Movember" %><h4><%= link_to "Support for $24.99", "https://vuier.com/v/the-men-of-movember-4d5e2d81-038b-4a57-a6aa-d124780eea18" %></h4></div>
		      </div>
		      <div class="row row-centered">
		        <div class="col-xs-4 col-centered"><%= link_to image_tag('movember2.png', class: 'img-responsive'), "https://vuier.com/v/the-men-of-movember-3cf5b0b1-3928-4a35-8fb3-5b6087dd89e6", alt: "Men of Movember" %><h4><%= link_to "Support for $49.99", "https://vuier.com/v/the-men-of-movember-3cf5b0b1-3928-4a35-8fb3-5b6087dd89e6" %></h4></div>
		        <div class="col-xs-4 col-centered"><%= link_to image_tag('MovemberThumbnail.png', class: 'img-responsive'), "https://vuier.com/v/the-men-of-movember-b05bf5a7-399c-47b7-8941-07537a3e9f00", alt: "Men of Movember" %><h4><%= link_to "Support for $74.99", "https://vuier.com/v/the-men-of-movember-b05bf5a7-399c-47b7-8941-07537a3e9f00" %></h4></div>
		        <div class="col-xs-4 col-centered"><%= link_to image_tag('movember2.png', class: 'img-responsive'), "https://vuier.com/v/the-men-of-movember-4b38b4ab-60b9-4aae-9108-32d995a648aa", alt: "Men of Movember" %><h4><%= link_to "Support for $99.99", "https://vuier.com/v/the-men-of-movember-4b38b4ab-60b9-4aae-9108-32d995a648aa" %></h4></div>
								
					<!-- </div> -->
				</div><!-- video-inline --><!-- /row -->
			</div><!--/container -->
		</div>
		